# Consul Discovery Configuration
application:
  discovery:
    backend: consul
  consul:
    host: ${CONSUL_HOST:localhost}
    port: ${CONSUL_PORT:8500}

spring:
  cloud:
    consul:
      discovery:
        enabled: true
        register: false
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
